name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://safe.global/cla' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          # user names of users allowed to contribute without CLA
          allowlist: DmitryBespalov,bot*
          # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          # enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          remote-organization-name: 'safe-global'
          # enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          remote-repository-name: 'cla-signatures'
